# Generated by Django 2.1 on 2018-09-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('nombr', models.CharField(max_length=30)),
                ('apell', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('es_admin', models.BooleanField(default=False)),
                ('es_maest', models.BooleanField(default=False)),
                ('es_activ', models.BooleanField(default=True)),
                ('fecha_ingre', models.DateTimeField(auto_now_add=True)),
                ('fecha_conex', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
